source 'https://rubygems.org'

gem 'sinatra'
gem 'rspec'
gem 'thin'
gem 'rack'
gem 'rack-test'
gem 'redis'
gem 'oauth2'
gem 'capistrano'
gem 'rvm-capistrano'
gem 'sprockets'
gem 'yui-compressor'
gem 'activesupport'
